import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  emptyStringAsUndefined: true,
  server: {
    DATABASE_URL: z.string().url(),
    GITHUB_CLIENT_ID: z.string(),
    GITHUB_CLIENT_SECRET: z.string(),
    GITHUB_CLIENT_ID_DEV: z.string(),
    GITHUB_CLIENT_SECRET_DEV: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    DATABASE_URL_UNPOOLED: z.string(),
    PGHOST: z.string(),
    PGHOST_UNPOOLED: z.string(),
    PGUSER: z.string(),
    PGDATABASE: z.string(),
    PGPASSWORD: z.string(),
    POSTGRES_URL: z.string(),
    POSTGRES_URL_NON_POOLING: z.string(),
    POSTGRES_USER: z.string(),
    POSTGRES_HOST: z.string(),
    POSTGRES_PASSWORD: z.string(),
    POSTGRES_DATABASE: z.string(),
    POSTGRES_URL_NO_SSL: z.string(),
    POSTGRES_PRISMA_URL: z.string(),
    HOME_URL: z.string(),
    OAUTH_CALLBACK: z.string(),
    LOCALHOST: z.string(),
    RESEND_KEY: z.string(),
    EMAIL_AUTH_PASS: z.string(),
  },
  experimental__runtimeEnv: process.env,
});
